# Generated by Django 4.1.5 on 2023-01-26 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="contestent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="singers/"),
                ),
                ("name", models.CharField(max_length=100)),
                ("voterid", models.IntegerField()),
                ("dzongkhag", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="AmountReceived",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("jrnlno", models.IntegerField()),
                ("amount", models.IntegerField()),
                ("date", models.CharField(max_length=100)),
                (
                    "contestent_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="amountreceived_set",
                        to="api.contestent",
                    ),
                ),
            ],
        ),
    ]
