# Generated by Django 4.1.5 on 2023-01-26 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="amountreceived",
            name="contestent_name",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="amountreceived",
            name="contestent_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.contestent"
            ),
        ),
    ]
