# Generated by Django 4.1.5 on 2023-01-26 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_amountreceived_contestent_name_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="amountreceived",
            old_name="contestent_id",
            new_name="contestent",
        ),
        migrations.RemoveField(model_name="amountreceived", name="contestent_name",),
    ]
