# Generated by Django 4.1.5 on 2023-01-26 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_rename_contestent_id_amountreceived_contestent_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="amountreceived",
            old_name="contestent",
            new_name="contestent_id",
        ),
    ]
