# Generated by Django 4.1.5 on 2023-02-05 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_rename_contestent_amountreceived_contestent_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="amountreceived",
            name="amount",
            field=models.IntegerField(verbose_name="amount"),
        ),
        migrations.AlterField(
            model_name="amountreceived",
            name="contestent_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="api.contestent",
                verbose_name="contestent_id",
            ),
        ),
        migrations.AlterField(
            model_name="amountreceived",
            name="date",
            field=models.CharField(max_length=100, verbose_name="date"),
        ),
        migrations.AlterField(
            model_name="amountreceived",
            name="jrnlno",
            field=models.IntegerField(unique=True, verbose_name="jrnlno"),
        ),
        migrations.AlterField(
            model_name="contestent",
            name="dzongkhag",
            field=models.CharField(max_length=100, verbose_name="dzongkhag"),
        ),
        migrations.AlterField(
            model_name="contestent",
            name="name",
            field=models.CharField(max_length=100, verbose_name="name"),
        ),
        migrations.AlterField(
            model_name="contestent",
            name="voterid",
            field=models.IntegerField(verbose_name="voterid"),
        ),
    ]
